services:
  web:
    build: .
    container_name: preorder_web
    restart: on-failure:5
    volumes:
      - ./files:/usr/app/files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8280:8280"