services:
  web:
    build: .
    container_name: preoder_web
    restart: on-failure:5
    volumes:
      - ./files:/usr/app/files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3000"