services:
  web:
    build: .
    container_name: preorder_web
    restart: on-failure:5
    volumes:
      - ./files:/usr/app/files
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    environment:
      - PORT=3000